# 文件名: .github/workflows/build-executable.yml

name: Build Windows Executable - PyInstaller (GitHub Artifacts)

on:
  push:
    branches:
      - main # 触发条件：当代码推送到 main 分支时

jobs:
  build:
    runs-on: windows-latest # 在 Windows 环境下运行

    steps:
    # 步骤 1: 检出（下载）你的代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤 2: 安装 Python 3.9
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # 步骤 3: 安装项目依赖 (PyInstaller 等)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller virtualenv

    # 步骤 4: 运行批处理文件来构建 .exe
    # 假设 build.bat 会在 'builder/pyinstaller' 目录下生成 .exe 文件
    - name: Run Batch File to Build Executable
      run: builder\pyinstaller\build.bat

    # 步骤 5: 压缩构建好的可执行文件
    - name: Compress executables with 7z
      run: |
        "C:\Program Files\7-Zip\7z.exe" a executables.7z *.exe -pprotected
      working-directory: ${{ github.workspace }}\builder\pyinstaller
      shell: cmd

    # 步骤 6: 上传构建产物到 GitHub
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        # 构建产物的名称，你下载时会看到这个名字
        name: windows-executables
        # 需要上传的文件路径
        # 这里我们上传 'builder/pyinstaller' 目录下的所有 .exe 文件和 .7z 压缩包
        path: |
          builder/pyinstaller/*.exe
          builder/pyinstaller/*.7z
